// <auto-generated />
namespace WebApiAuthCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commentsIListCarModelCarsiproductsmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentsIListCarModelCarsiproductsmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202012252114484_comments IList CarModel Cars i products model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
