// <auto-generated />
namespace WebApiAuthCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_in_product_model_from_string_to_in : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_in_product_model_from_string_to_in));
        
        string IMigrationMetadata.Id
        {
            get { return "202012290656456_change_in_product_model_from_string_to_in"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
