// <auto-generated />
namespace WebApiAuthCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_ProductModel_Required_false_for_foreign_Ids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_ProductModel_Required_false_for_foreign_Ids));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101715509_Change_ProductModel_Required_false_for_foreign_Id-s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
